using System;
using System.IO;
using System.Text;
using ExcelToJsonPlugin.Editor.Core.Models;

namespace ExcelToJsonPlugin.Editor.Generator
{
    /// <summary>
    /// 从 TableSchema 生成 C# 源代码。
    /// 产出两类文件：
    ///   1. Row 类（数据行，partial class，[Serializable]）
    ///   2. Table 类（ScriptableObject 容器，继承 BaseDataTable&lt;TRow&gt;）
    /// </summary>
    public static class CodeGenerator
    {
        /// <summary>
        /// 生成配置。
        /// </summary>
        public class Config
        {
            /// <summary>Row 类输出目录（相对于 Assets/）</summary>
            public string RowOutputDir { get; set; } = "Scripts/Generated/Data";

            /// <summary>Table 类输出目录（相对于 Assets/）</summary>
            public string TableOutputDir { get; set; } = "Scripts/Generated/Tables";

            /// <summary>C# 命名空间</summary>
            public string Namespace { get; set; } = "Game.Data";

            /// <summary>Row 类后缀（如 ItemRow）</summary>
            public string RowSuffix { get; set; } = "Row";

            /// <summary>Table 类后缀（如 ItemTable）</summary>
            public string TableSuffix { get; set; } = "Table";

            /// <summary>项目 Assets 根目录</summary>
            public string AssetsRoot { get; set; } = "Assets";
        }

        /// <summary>
        /// 生成 Row 代码（字符串）。
        /// </summary>
        public static string GenerateRowClass(TableSchema schema, Config config)
        {
            var sb = new StringBuilder();
            var className = GetRowClassName(schema.TableName, config);
            var idFieldName = schema.Fields.Count > 0 ? schema.Fields[0].CsFieldName : "id";

            // 文件头注释
            sb.AppendLine("// ===== Auto-generated by ExcelToJSON =====");
            sb.AppendLine($"// Source: {schema.FileName} → Sheet: {schema.TableName}");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// DO NOT EDIT — will be overwritten on re-export.");
            sb.AppendLine("// Add custom logic in a separate partial class file.");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {config.Namespace}");
            sb.AppendLine("{");

            // 类声明
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// 数据行类。来源: {schema.FileName} / {schema.TableName}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    [Serializable]");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");

            // 字段
            foreach (var field in schema.Fields)
            {
                var tooltip = string.IsNullOrEmpty(field.Comment)
                    ? field.Name
                    : field.Comment.Replace("\"", "\\\"");

                sb.AppendLine($"        [Tooltip(\"{tooltip}\")]");
                sb.AppendLine($"        public {field.CsTypeName} {field.CsFieldName};");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 生成 Table 容器类代码（字符串）。
        /// </summary>
        public static string GenerateTableClass(TableSchema schema, Config config)
        {
            var sb = new StringBuilder();
            var tableClassName = GetTableClassName(schema.TableName, config);
            var rowClassName = GetRowClassName(schema.TableName, config);
            var idField = schema.Fields.Count > 0 ? schema.Fields[0] : null;
            var idFieldName = idField?.CsFieldName ?? "id";

            sb.AppendLine("// ===== Auto-generated by ExcelToJSON =====");
            sb.AppendLine($"// Source: {schema.FileName} → Sheet: {schema.TableName}");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using ExcelToJsonPlugin.Runtime;");
            sb.AppendLine();
            sb.AppendLine($"namespace {config.Namespace}");
            sb.AppendLine("{");

            // CreateAssetMenu
            sb.AppendLine($"    [CreateAssetMenu(fileName = \"{schema.TableName}\", ");
            sb.AppendLine($"        menuName = \"Game Data/{schema.TableName} Table\")]");
            sb.AppendLine($"    public class {tableClassName} : BaseDataTable<{rowClassName}>");
            sb.AppendLine("    {");

            // TableName override
            sb.AppendLine($"        public override string TableName => \"{schema.TableName}\";");
            sb.AppendLine();

            // GetRowId override
            sb.AppendLine($"        protected override int GetRowId({rowClassName} row)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return row.{idFieldName};");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 将生成的代码写入磁盘。
        /// </summary>
        /// <returns>(rowFilePath, tableFilePath)</returns>
        public static (string rowPath, string tablePath) WriteToDisk(
            TableSchema schema,
            Config config)
        {
            var rowCode = GenerateRowClass(schema, config);
            var tableCode = GenerateTableClass(schema, config);

            var rowDir = Path.Combine(config.AssetsRoot, config.RowOutputDir);
            var tableDir = Path.Combine(config.AssetsRoot, config.TableOutputDir);

            Directory.CreateDirectory(rowDir);
            Directory.CreateDirectory(tableDir);

            var rowClassName = GetRowClassName(schema.TableName, config);
            var tableClassName = GetTableClassName(schema.TableName, config);

            var rowPath = Path.Combine(rowDir, $"{rowClassName}.cs");
            var tablePath = Path.Combine(tableDir, $"{tableClassName}.cs");

            File.WriteAllText(rowPath, rowCode, Encoding.UTF8);
            File.WriteAllText(tablePath, tableCode, Encoding.UTF8);

            return (rowPath, tablePath);
        }

        // ============================================================
        // 命名工具
        // ============================================================

        public static string GetRowClassName(string tableName, Config config)
        {
            return ToPascalCase(tableName) + config.RowSuffix;
        }

        public static string GetTableClassName(string tableName, Config config)
        {
            return ToPascalCase(tableName) + config.TableSuffix;
        }

        /// <summary>
        /// 将任意字符串转为 PascalCase。
        /// 如 "weapon_data" → "WeaponData"，"武器数据" → "WuQiShuJu"（简单处理）
        /// </summary>
        private static string ToPascalCase(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "Unknown";

            var sb = new StringBuilder();
            bool nextUpper = true;

            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c))
                {
                    if (nextUpper)
                    {
                        sb.Append(char.ToUpperInvariant(c));
                        nextUpper = false;
                    }
                    else
                    {
                        sb.Append(c);
                    }
                }
                else if (c == '_' || c == '-' || c == ' ')
                {
                    nextUpper = true;
                }
                // 中文字符：直接用（C# 支持 Unicode 类名）
                else if (c >= 0x4E00 && c <= 0x9FFF)
                {
                    sb.Append(c);
                    nextUpper = false;
                }
            }

            var result = sb.ToString();
            if (string.IsNullOrEmpty(result))
                return "Unknown";

            return result;
        }
    }
}
